

runfile('C:/Users/User/Desktop/GitHub/file.py', wdir='C:/Users/User/Desktop/GitHub')
Traceback (most recent call last):

  File "<ipython-input-32-ade7880b4584>", line 1, in <module>
    runfile('C:/Users/User/Desktop/GitHub/file.py', wdir='C:/Users/User/Desktop/GitHub')

  File "C:\Users\User\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\User\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/User/Desktop/GitHub/file.py", line 15, in <module>
    print(ele)

TypeError: 'NoneType' object is not callable




runfile('C:/Users/User/Desktop/GitHub/file.py', wdir='C:/Users/User/Desktop/GitHub')
Traceback (most recent call last):

  File "<ipython-input-33-ade7880b4584>", line 1, in <module>
    runfile('C:/Users/User/Desktop/GitHub/file.py', wdir='C:/Users/User/Desktop/GitHub')

  File "C:\Users\User\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\User\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/User/Desktop/GitHub/file.py", line 16, in <module>
    print("=================================")

TypeError: 'NoneType' object is not callable




runfile('C:/Users/User/Desktop/GitHub/file.py', wdir='C:/Users/User/Desktop/GitHub')
Traceback (most recent call last):

  File "<ipython-input-34-ade7880b4584>", line 1, in <module>
    runfile('C:/Users/User/Desktop/GitHub/file.py', wdir='C:/Users/User/Desktop/GitHub')

  File "C:\Users\User\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\User\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/User/Desktop/GitHub/file.py", line 15, in <module>
    print(ele)

TypeError: 'NoneType' object is not callable




runfile('C:/Users/User/Desktop/GitHub/class3.py', wdir='C:/Users/User/Desktop/GitHub')
Traceback (most recent call last):

  File "<ipython-input-35-d7f76522cecf>", line 1, in <module>
    runfile('C:/Users/User/Desktop/GitHub/class3.py', wdir='C:/Users/User/Desktop/GitHub')

  File "C:\Users\User\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\User\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/User/Desktop/GitHub/class3.py", line 16, in <module>
    print("=================================")

TypeError: 'NoneType' object is not callable




runfile('C:/Users/User/Desktop/GitHub/class3.py', wdir='C:/Users/User/Desktop/GitHub')
Traceback (most recent call last):

  File "<ipython-input-36-d7f76522cecf>", line 1, in <module>
    runfile('C:/Users/User/Desktop/GitHub/class3.py', wdir='C:/Users/User/Desktop/GitHub')

  File "C:\Users\User\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\User\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/User/Desktop/GitHub/class3.py", line 17, in <module>
    print("=================================")

TypeError: 'NoneType' object is not callable




runfile('C:/Users/User/Desktop/GitHub/class3.py', wdir='C:/Users/User/Desktop/GitHub')
Traceback (most recent call last):

  File "<ipython-input-37-d7f76522cecf>", line 1, in <module>
    runfile('C:/Users/User/Desktop/GitHub/class3.py', wdir='C:/Users/User/Desktop/GitHub')

  File "C:\Users\User\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\User\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/User/Desktop/GitHub/class3.py", line 17, in <module>
    print("=============================")

TypeError: 'NoneType' object is not callable




runfile('C:/Users/User/Desktop/GitHub/class3.py', wdir='C:/Users/User/Desktop/GitHub')
Traceback (most recent call last):

  File "<ipython-input-38-d7f76522cecf>", line 1, in <module>
    runfile('C:/Users/User/Desktop/GitHub/class3.py', wdir='C:/Users/User/Desktop/GitHub')

  File "C:\Users\User\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\User\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/User/Desktop/GitHub/class3.py", line 16, in <module>
    print(ele)

TypeError: 'NoneType' object is not callable




runfile('C:/Users/User/Desktop/GitHub/class3.py', wdir='C:/Users/User/Desktop/GitHub')

runfile('C:/Users/User/Desktop/GitHub/class3.py', wdir='C:/Users/User/Desktop/GitHub')
Traceback (most recent call last):

  File "<ipython-input-40-d7f76522cecf>", line 1, in <module>
    runfile('C:/Users/User/Desktop/GitHub/class3.py', wdir='C:/Users/User/Desktop/GitHub')

  File "C:\Users\User\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\User\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/User/Desktop/GitHub/class3.py", line 17, in <module>
    print('=============================')

TypeError: 'NoneType' object is not callable